import AppKit
import SwiftUI

/// The two marks the interface shows, loaded once.
///
/// The bundle resolves differently under `swift run` (beside the executable)
/// and inside a packaged `.app` (in `Contents/Resources`, put there by
/// `scripts/release.sh`). Every mark is optional and every call site degrades
/// rather than traps, because a decoration must never be able to stop the app
/// from opening.
enum Brand {
    /// Charis Tsevis's maker's mark. Shown at 20pt, so the 40pt asset is its @2x.
    static let makersMark: NSImage? = load("TsevisMark")

    /// CrewListr Pro's own icon, masked to the macOS shape.
    static let appMark: NSImage? = load("AppMark")

    /// Union Yachting's mark, and the photograph behind the info screen's
    /// lockup — an aerial of a wake that happens to draw their own logo on the
    /// water, which is why it is the key art rather than a stock sea.
    static let unionMark: NSImage? = load("UnionMark")
    static let unionBanner: NSImage? = load("UnionBanner", extension: "jpg")

    static let unionName = "Union Yachting"
    static let unionSite = URL(string: "https://www.unionyachting.com")!

    /// The person, for the mark's tooltip and accessibility label.
    static let makerName = "Charis Tsevis"
    /// The studio, for the credit line an operator reads on the info screen.
    static let studioName = "Tsevis Studio"
    static let makerSite = URL(string: "https://tsevis.com")!

    /// Where the marks live, found without ever trapping.
    ///
    /// This used to be `Bundle.module`. That accessor is generated by SwiftPM
    /// and ends in `fatalError` when it cannot find the bundle, so the "degrade
    /// rather than trap" contract above was never actually kept: the trap fired
    /// inside the accessor, before `load`'s `guard` could run.
    ///
    /// It fired for real. SwiftPM emits the resource bundle as a bare directory
    /// with no `Info.plist`; macOS 26 will not accept such a directory as a
    /// bundle, `Bundle(url:)` returned nil for every candidate, and the app
    /// trapped in `MakersMark.body` while its first window was being built —
    /// which reads to the operator as an app that opens and instantly quits.
    /// `scripts/release.sh` now writes that `Info.plist`, and this resolves the
    /// bundle where "not found" is a value rather than a crash.
    private static let resourceBundle: Bundle = {
        let name = "CrewListrProMac_CrewListrProMac.bundle"
        let host = Bundle(for: BundleLocator.self)
        let candidates = [
            Bundle.main.resourceURL,    // a packaged .app: Contents/Resources
            Bundle.main.bundleURL,      // `swift run`: beside the executable
            host.resourceURL,
            host.bundleURL,
            // `swift test`: the bundle is a sibling of the .xctest, not inside
            // it. Leaving this out is what made every mark nil under test while
            // the packaged app was fine — the exact inverse of the bug above.
            host.bundleURL.deletingLastPathComponent(),
        ]
        for case let directory? in candidates {
            if let bundle = Bundle(url: directory.appending(path: name)) { return bundle }
        }
        // Nothing nested resolved. The images may still sit directly in the
        // app's own Resources, and if they do not, `load` returns nil and the
        // interface shows its text fallback.
        return .main
    }()

    /// Only here to give `Bundle(for:)` a class in this module to locate.
    private final class BundleLocator {}

    private static func load(_ name: String, extension ext: String = "png") -> NSImage? {
        guard let url = resourceBundle.url(forResource: name, withExtension: ext),
              let image = NSImage(contentsOf: url) else { return nil }
        return image
    }
}

/// Philon's `.makers-mark`: fixed to the lower-left of the window, 20pt, at
/// 55% until the pointer is over it.
///
/// It sits in a window-level overlay rather than inside a column, because a
/// sidebar can be collapsed and the mark should not go with it.
struct MakersMark: View {
    /// Art, padding and bottom inset. Any layout sharing the corner reserves
    /// this much so the mark never lands on a control.
    static let reservedHeight: CGFloat = 20 + 3 * 2 + 9

    @State private var hovering = false
    @Environment(\.openURL) private var openURL

    var body: some View {
        Button {
            openURL(Brand.makerSite)
        } label: {
            Group {
                if let mark = Brand.makersMark {
                    Image(nsImage: mark).resizable().interpolation(.high)
                } else {
                    // The bundle is missing: keep the affordance, drop the art.
                    Text("CT")
                        .font(.system(size: 9, weight: .bold))
                        .foregroundStyle(Theme.inkTertiary)
                }
            }
            .frame(width: 20, height: 20)
            .padding(3)
            .background(
                RoundedRectangle(cornerRadius: Theme.Radius.inner, style: .continuous)
                    .fill(hovering ? Theme.controlTrack : Color.clear)
            )
        }
        .buttonStyle(.plain)
        .opacity(hovering ? 1 : 0.55)
        .onHover { hovering = $0 }
        .animation(.easeOut(duration: 0.16), value: hovering)
        .help("Made by \(Brand.makerName) — tsevis.com")
        .accessibilityLabel("Made by \(Brand.makerName). Opens tsevis.com.")
        .padding(.leading, 13)
        .padding(.bottom, 9)
    }
}
