// Generated from the "Nationalities - Ιθαγένειες" sheet of
// docs/passengers_manifest_template.xlsx. Regenerate rather than edit: the
// codes are the importer's, not ISO's — Palestine is TPO, Kosovo XKX,
// stateless XXX.

extension ManifestNationality {
    /// Code, English adjective, Greek adjective — in the template's order.
    static let table: [(code: String, english: String, greek: String)] = [
        ("AFG", "Afghan", "Αφγανική"),
        ("ALB", "Albanian", "Αλβανική"),
        ("DZA", "Algerian", "Αλγερινή"),
        ("AND", "Andorran", "Ανδορρανή"),
        ("AGO", "Angolan", "Αγκολέζικη"),
        ("ATG", "Antiguan", "Αντιγκουανή"),
        ("ARG", "Argentine", "Αργεντινή"),
        ("ARM", "Armenian", "Αρμενική"),
        ("AUS", "Australian", "Αυστραλιανή"),
        ("AUT", "Austrian", "Αυστριακή"),
        ("AZE", "Azerbaijani", "Αζερμπαϊτζανική"),
        ("BHS", "Bahamian", "Μπαχαμιανή"),
        ("BHR", "Bahraini", "Μπαχρεϊνή"),
        ("BGD", "Bangladeshi", "Μπανγκλαντεσιανή"),
        ("BRB", "Barbadian", "Μπαρμπαντιανή"),
        ("BLR", "Belarusian", "Λευκορωσική"),
        ("BEL", "Belgian", "Βελγική"),
        ("BLZ", "Belizean", "Μπελιζιανή"),
        ("BEN", "Beninese", "Μπενινέζικη"),
        ("BTN", "Bhutanese", "Μπουτανέζικη"),
        ("BOL", "Bolivian", "Βολιβιανή"),
        ("BIH", "Bosnian", "Βοσνιακή"),
        ("BWA", "Botswanan", "Μποτσουανή"),
        ("BRA", "Brazilian", "Βραζιλιάνικη"),
        ("BRN", "Bruneian", "Μπρουνεϊανή"),
        ("BGR", "Bulgarian", "Βουλγαρική"),
        ("BFA", "Burkinabe", "Μπουρκινιανή"),
        ("BDI", "Burundian", "Μπουρουντιανή"),
        ("CPV", "Cape Verdean", "Πρασινοακρωτηριανή"),
        ("KHM", "Cambodian", "Καμποτζιανή"),
        ("CMR", "Cameroonian", "Καμερουνέζικη"),
        ("CAN", "Canadian", "Καναδική"),
        ("CAF", "Central African", "Κεντροαφρικανική"),
        ("TCD", "Chadian", "Τσαντιανή"),
        ("CHL", "Chilean", "Χιλιανή"),
        ("CHN", "Chinese", "Κινεζική"),
        ("COL", "Colombian", "Κολομβιανή"),
        ("COM", "Comorian", "Κομοριανή"),
        ("COD", "Congolese (DRC)", "Κονγκολέζικη (ΛΔΚ)"),
        ("COG", "Congolese", "Κονγκολέζικη"),
        ("CRI", "Costa Rican", "Κοσταρικανή"),
        ("HRV", "Croatian", "Κροατική"),
        ("CUB", "Cuban", "Κουβανική"),
        ("CYP", "Cypriot", "Κυπριακή"),
        ("CZE", "Czech", "Τσεχική"),
        ("DNK", "Danish", "Δανική"),
        ("DJI", "Djiboutian", "Τζιμπουτιανή"),
        ("DOM", "Dominican", "Δομινικανή"),
        ("DMA", "Commonwealth of Dominica", "Κοινοπολιτεία της Δομινίκας"),
        ("ECU", "Ecuadorian", "Εκουαδοριανή"),
        ("EGY", "Egyptian", "Αιγυπτιακή"),
        ("SLV", "Salvadoran", "Σαλβαδοριανή"),
        ("GNQ", "Equatoguinean", "Ισημερινογουινεανή"),
        ("ERI", "Eritrean", "Ερυθραϊκή"),
        ("EST", "Estonian", "Εσθονική"),
        ("SWZ", "Swazi", "Σουαζιλανδική"),
        ("ETH", "Ethiopian", "Αιθιοπική"),
        ("FJI", "Fijian", "Φιτζιανή"),
        ("FIN", "Finnish", "Φινλανδική"),
        ("FRA", "French", "Γαλλική"),
        ("GAB", "Gabonese", "Γκαμπονέζικη"),
        ("GMB", "Gambian", "Γκάμπιανη"),
        ("GEO", "Georgian", "Γεωργιανή"),
        ("DEU", "German", "Γερμανική"),
        ("GHA", "Ghanaian", "Γκανέζικη"),
        ("GRC", "Greek", "Ελληνική"),
        ("GRD", "Grenadian", "Γρεναδιανή"),
        ("GTM", "Guatemalan", "Γουατεμαλανή"),
        ("GIN", "Guinean", "Γουινεανή"),
        ("GNB", "Bissau-Guinean", "Γουινεοβισσαουανή"),
        ("GUY", "Guyanese", "Γουιανέζικη"),
        ("HTI", "Haitian", "Αϊτινή"),
        ("HND", "Honduran", "Ονδουριανή"),
        ("HUN", "Hungarian", "Ουγγρική"),
        ("ISL", "Icelandic", "Ισλανδική"),
        ("IND", "Indian", "Ινδική"),
        ("IDN", "Indonesian", "Ινδονησιακή"),
        ("IRN", "Iranian", "Ιρανική"),
        ("IRQ", "Iraqi", "Ιρακινή"),
        ("IRL", "Irish", "Ιρλανδική"),
        ("ISR", "Israeli", "Ισραηλινή"),
        ("ITA", "Italian", "Ιταλική"),
        ("CIV", "Ivorian", "Ακτής Ελεφαντοστού"),
        ("JAM", "Jamaican", "Τζαμαϊκανή"),
        ("JPN", "Japanese", "Ιαπωνική"),
        ("JOR", "Jordanian", "Ιορδανική"),
        ("KAZ", "Kazakhstani", "Καζακστανική"),
        ("KEN", "Kenyan", "Κενυατική"),
        ("KIR", "I-Kiribati", "Κιριμπατιανή"),
        ("PRK", "North Korean", "Βορειοκορεατική"),
        ("KOR", "South Korean", "Νοτιοκορεατική"),
        ("KWT", "Kuwaiti", "Κουβεϊτιανή"),
        ("KGZ", "Kyrgyz", "Κιργιζική"),
        ("LAO", "Laotian", "Λαοτινή"),
        ("LVA", "Latvian", "Λετονική"),
        ("LBN", "Lebanese", "Λιβανέζικη"),
        ("LSO", "Basotho", "Λεσοθιανή"),
        ("LBR", "Liberian", "Λιβεριανή"),
        ("LBY", "Libyan", "Λιβυκή"),
        ("LIE", "Liechtenstein", "Λιχτενστάιν"),
        ("LTU", "Lithuanian", "Λιθουανική"),
        ("LUX", "Luxembourgish", "Λουξεμβουργιανή"),
        ("MDG", "Malagasy", "Μαδαγασκαρική"),
        ("MWI", "Malawian", "Μαλαουιανή"),
        ("MYS", "Malaysian", "Μαλαισιανή"),
        ("MDV", "Maldivian", "Μαλδιβιανή"),
        ("MLI", "Malian", "Μαλιανή"),
        ("MLT", "Maltese", "Μαλτέζικη"),
        ("MHL", "Marshallese", "Νήσων Μάρσαλ"),
        ("MRT", "Mauritanian", "Μαυριτανική"),
        ("MUS", "Mauritian", "Μαυρικιανή"),
        ("MEX", "Mexican", "Μεξικανική"),
        ("FSM", "Micronesian", "Μικρονησιακή"),
        ("MDA", "Moldovan", "Μολδαβική"),
        ("MCO", "Monacan", "Μονεγασκική"),
        ("MNG", "Mongolian", "Μογγολική"),
        ("MNE", "Montenegrin", "Μαυροβουνιώτικη"),
        ("MAR", "Moroccan", "Μαροκινή"),
        ("MOZ", "Mozambican", "Μοζαμβικανή"),
        ("MMR", "Burmese", "Βιρμανική"),
        ("NAM", "Namibian", "Ναμίμπιανη"),
        ("NRU", "Nauruan", "Ναουρουανή"),
        ("NPL", "Nepali", "Νεπαλική"),
        ("NLD", "Dutch", "Ολλανδική"),
        ("NZL", "New Zealander", "Νεοζηλανδική"),
        ("NIC", "Nicaraguan", "Νικαραγουανή"),
        ("NER", "Nigerien", "Νιγηριανή (Νίγηρας)"),
        ("NGA", "Nigerian", "Νιγηριανή"),
        ("MKD", "Macedonian", "Βορειομακεδονική"),
        ("NOR", "Norwegian", "Νορβηγική"),
        ("OMN", "Omani", "Ομανική"),
        ("PAK", "Pakistani", "Πακιστανική"),
        ("PLW", "Palauan", "Παλαουανή"),
        ("PAN", "Panamanian", "Παναμανική"),
        ("PNG", "Papua New Guinean", "Παπουανή"),
        ("PRY", "Paraguayan", "Παραγουανή"),
        ("PER", "Peruvian", "Περουβιανή"),
        ("PHL", "Filipino", "Φιλιππινέζικη"),
        ("POL", "Polish", "Πολωνική"),
        ("PRT", "Portuguese", "Πορτογαλική"),
        ("QAT", "Qatari", "Καταριανή"),
        ("ROU", "Romanian", "Ρουμανική"),
        ("RUS", "Russian", "Ρωσική"),
        ("RWA", "Rwandan", "Ρουαντέζικη"),
        ("KNA", "Kittitian", "Αγίου Χριστοφόρου"),
        ("LCA", "Saint Lucian", "Αγίας Λουκίας"),
        ("VCT", "Vincentian", "Αγίου Βικεντίου"),
        ("WSM", "Samoan", "Σαμοανή"),
        ("SMR", "Sammarinese", "Σαν Μαρινέζικη"),
        ("STP", "Sao Tomean", "Σάο Τομέ"),
        ("SAU", "Saudi", "Σαουδαραβική"),
        ("SEN", "Senegalese", "Σενεγαλέζικη"),
        ("SRB", "Serbian", "Σερβική"),
        ("SYC", "Seychellois", "Σεϋχελλιανή"),
        ("SLE", "Sierra Leonean", "Σιέρα Λεόνε"),
        ("SGP", "Singaporean", "Σιγκαπουρανή"),
        ("SVK", "Slovak", "Σλοβακική"),
        ("SVN", "Slovenian", "Σλοβενική"),
        ("SLB", "Solomon Islander", "Νήσων Σολομώντος"),
        ("SOM", "Somali", "Σομαλική"),
        ("ZAF", "South African", "Νοτιοαφρικανική"),
        ("SSD", "South Sudanese", "Νοτιοσουδανική"),
        ("ESP", "Spanish", "Ισπανική"),
        ("LKA", "Sri Lankan", "Σριλανκέζικη"),
        ("SDN", "Sudanese", "Σουδανική"),
        ("SUR", "Surinamese", "Σουρινάμ"),
        ("SWE", "Swedish", "Σουηδική"),
        ("CHE", "Swiss", "Ελβετική"),
        ("SYR", "Syrian", "Συριακή"),
        ("TWN", "Taiwanese", "Ταϊβανέζικη"),
        ("TJK", "Tajik", "Τατζικιστανική"),
        ("TZA", "Tanzanian", "Τανζανική"),
        ("THA", "Thai", "Ταϊλανδική"),
        ("TLS", "Timorese", "Ανατολικοτιμορέζικη"),
        ("TGO", "Togolese", "Τογκολέζικη"),
        ("TPO", "Palestinian", "Παλαιστινιακή"),
        ("TON", "Tongan", "Τονγκανή"),
        ("TTO", "Trinidadian", "Τρινιντανή"),
        ("TUN", "Tunisian", "Τυνησιακή"),
        ("TUR", "Turkish", "Τουρκική"),
        ("TKM", "Turkmen", "Τουρκμενική"),
        ("TUV", "Tuvaluan", "Τουβαλουανή"),
        ("UGA", "Ugandan", "Ουγκαντέζικη"),
        ("UKR", "Ukrainian", "Ουκρανική"),
        ("ARE", "Emirati", "Εμιρατιανή"),
        ("GBR", "British", "Βρετανική"),
        ("USA", "American", "Αμερικανική"),
        ("URY", "Uruguayan", "Ουρουγουανή"),
        ("UZB", "Uzbek", "Ουζμπεκική"),
        ("VUT", "Ni-Vanuatu", "Βανουατουανή"),
        ("VEN", "Venezuelan", "Βενεζουελανή"),
        ("VNM", "Vietnamese", "Βιετναμέζικη"),
        ("YEM", "Yemeni", "Υεμενιτική"),
        ("ZMB", "Zambian", "Ζάμπιανη"),
        ("ZWE", "Zimbabwean", "Ζιμπαμπουανή"),
        ("XKX", "Kosovo", "Κόσοβο"),
        ("XXX", "Stateless", "Ανιθαγενής"),
    ]
}
